Result refactor/#137
Myongji-Graduate/myongji-graduate-next pull request #140
Opened 2024-09-05 13:16 UTC by yougyung

## **📌** 작업 내용
결과페이지 및 로그인페이지에 있는 개선 사항들을 수정했습니다

https://github.com/user-attachments/assets/4c4c1597-49f3-451b-85bd-677799f309b9

> 구현 내용 및 작업 했던 내역

- [x] 카테고리별 진행률 0% 의 경우 게이지 hidden
- [x] 아이디 찾기, 비밀번호 찾기 redirect
- [x] result page 스켈레톤 높이 조절
- [x] 성적표 결과 일반교양의 채플관련 안내
- [x] 카테고리별 만족도에 따른 차트 색상 처리(파란색)
- [x] 이수과목 없는 경우 안내문구 제공 

<img width="300" alt="스크린샷 2024-09-05 오후 10 10 34" src="https://github.com/user-attachments/assets/e116aff6-2a63-4ae7-bbb7-93ec3f1a72da">

2024-09-06 03:28 UTC, gahyuun requested changes
<img width="931" alt="image" src="https://github.com/user-attachments/assets/fdfb0aa9-7eb5-4551-81c4-cd6d26231523">
-21 학점으로 노출되는 텍스트, 학점이 부족한데 100%로 보이는 것에 대해 수정이 필요할 것 같아요

2024-09-06 03:38 UTC, gahyuun requested changes
https://github.com/user-attachments/assets/6e219d76-92eb-4f79-9aab-d25a42e73d9a

일반 교양이 두 번 보입니다 확인 부탁드립니다 !

2024-09-06 03:38 UTC, gahyuun commented on app/ui/user/user-info-card/user-info-card.tsx
> +    return isInitUser(data) ? <></> : <UserInfoContent data={data} />;
분기처리를 하는 컴포넌트가 아니므로 저도 단언이 더 적절하다고 생각합니다

2024-09-06 03:38 UTC, gahyuun commented on app/ui/result/result-category-detail-lecture/result-cagegory-detail-lecture.tsx
> +        </>
<img width="1087" alt="image" src="https://github.com/user-attachments/assets/b99e50e7-3bf8-4f91-bec1-97e9b19d7ab9">
이수한 과목이 없을 때 나타나는 선을 지워야할 것 같습니다. 
또한 이수한 과목이 없는 건데, 체크 이모지가 적절하지 않은 것 같습니다!

UI가 일관되는 게 더 나을 것 같아 테이블 컴포넌트를 제거 할 필요는 없어보입니다

2024-09-06 03:38 UTC, gahyuun commented on app/ui/result/result-category-detail-content/result-category-detail-content.tsx
<img width="345" alt="image" src="https://github.com/user-attachments/assets/d481d0be-91ba-4c9a-99f6-cd5b76acc9a4">
기준학점보다 이수학점이 더 많을 때 파란색으로 숫자를 표기하는 게 더 낫지않을까요?

2024-09-06 03:38 UTC, gahyuun requested changes
https://github.com/user-attachments/assets/6e219d76-92eb-4f79-9aab-d25a42e73d9a

일반 교양이 두 번 보입니다 확인 부탁드립니다 !

2024-09-06 04:46 UTC, yougyung commented on app/ui/result/result-category-detail-content/result-category-detail-content.tsx
a606dcadd773ce5bba4ce555e8b7cd43543b5822

2024-09-06 04:47 UTC, yougyung commented
> 2024-09-06.12.38.24.mov 
> 일반 교양이 두 번 보입니다 확인 부탁드립니다 !

정말정말 감사합니다 .......! e3915c242b6dc9dd6277faaf774250a0ea496a69

2024-09-06 04:49 UTC, yougyung commented
> <img alt="image" width="931" src="https://private-user-images.githubusercontent.com/81469686/365023833-fdfb0aa9-7eb5-4551-81c4-cd6d26231523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTcyNjUsIm5iZiI6MTcyNTU5Njk2NSwicGF0aCI6Ii84MTQ2OTY4Ni8zNjUwMjM4MzMtZmRmYjBhYTktN2ViNS00NTUxLTgxYzQtY2Q2ZDI2MjMxNTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA0MjkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyN2Y3Y2VmZDA2MDVjN2RiMDI3YTZkYzU1YTYzMjRiZjAzMDI3NDI0ZTIyNTQyMzgzYjg3Mzk4MDljYzYxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LGuqj00BMpB9EJsDdOHJ8zVLObt-kAJGI1EIeFEcEb4"> -21 학점으로 노출되는 텍스트, 학점이 부족한데 100%로 보이는 것에 대해 수정이 필요할 것 같아요

다음 PR로 졸업만족여부에 따라 다르게 텍스트를 노출하는 기능이 올라갈 예정입니다. 해당 과정에서 관련 문제를 해결하도록 할게요 !

2024-09-06 05:51 UTC, seonghunYang commented on app/ui/user/user-info-card/user-info-card.tsx
> +    return isInitUser(data) ? <></> : <UserInfoContent data={data} />;
도움이 필요한 부분 잘 읽어봤습니다. 제 생각에는 타입 단언보다 기존 코드가 더 적절합니다. 이유는 타입 단언을 사용하면 논리적 문제가 생기고 예기치 않은 오류가 발생할 수 있기 때문입니다.

user-info-card는 user 도메인에 위치한 도메인 컴포넌트이므로, 이 컴포넌트가 어느 페이지에서 사용되는지는 관심사를 벗어납니다. 현재 논의에서는 이 컴포넌트가 결과 페이지에서만 사용된다고 가정하고 initUser를 고려하지 않아도 된다고 생각하지만, 실제로는 어느 페이지에서 이 컴포넌트가 재사용될지 모르기 때문에 타입 단언을 사용하면 재사용성이 떨어질 수 있습니다.

물론 타입 단언을 해도 당장은 문제가 생기지 않겠지만, 이 컴포넌트는 result 페이지와 같이 유저가 이미 초기화된 곳에서만 사용할 수 있게 됩니다. 오히려 이렇게 되면 코드를 이해하기 더 어렵게 만들고 재사용성을 떨어트린다 생각합니다. 예를 들어, 새로운 동료 개발자가 새 페이지를 개발하면서 이 컴포넌트를 재사용하려 할 때, 초기화되지 않은 유저로 인해 예상치 못한 문제가 발생할 수 있습니다. 

해결 방법은 두 가지가 있습니다. 첫째, 기존대로 초기화되지 않은 유저를 처리하는 로직을 만드는 것입니다. 둘째, 만약 이 컴포넌트가 결과 페이지 외에는 사용되지 않을 것이 확실하기에 재사용성을 고려하고 싶지 않다면, 아키텍처상 위치를 변경하여 결과 페이지 전용 컴포넌트임을 명확히 하는 것입니다.

번외로 저는 기존 InitUserAnnounce 컴포넌트처럼 (아니면 컴포넌트 명을 차라리 NoData와 같이 문제가 있음을 나타내는 방식으로 표현해도 됩니다) "성적표 PDF를 업로드해야 졸업사정 결과를 확인할 수 있어요."라고 알려주는 게 동료 개발자가 코드를 읽을 때도 더 이해가 잘 될 거라고 생각이 드네요.

2024-09-06 06:19 UTC, yougyung commented on app/ui/result/result-category-detail-lecture/result-cagegory-detail-lecture.tsx
> +        </>
86f417d8dc73d1962a0d67ead3abfca61c499ab1

2024-09-06 06:30 UTC, yougyung commented on app/ui/user/user-info-card/user-info-card.tsx
> +    return isInitUser(data) ? <></> : <UserInfoContent data={data} />;
user-info-card가 도메인 컴포넌트라는 가정을 놓치고 있었네요. 의견 감사합니다! bbb0101f7503f242922a5bb22f1f4613a366d75d

2024-09-07 03:50 UTC, gahyuun approved these changes

2024-09-07 12:12 UTC, seonghunYang approved these changes
수고하셨습니다

2024-09-07 12:13 UTC, merged