implement List molecule component/#18
Myongji-Graduate/myongji-graduate-next pull request #27
Opened 2024-02-16 16:47 UTC by gahyuun

## **📌** 작업 내용

 

> 구현 내용 및 작업 했던 내역

- [x] list molecule component 구현 
추가,삭제 버튼이 list row에 존재할 수 있도록 수정이 필요합니다!
이 부분은 기이수 과목 삭제 기능을 구현하면서 수정 할 예정입니다

## 🤔 고민 했던 부분
- list row 컴포넌트에서 column이 일정하게 정해진 크기를 가져야합니다. 처음에는 table 태그를 사용해서` table-layout: fixed;` 
속성을 사용하려 했지만, 아래 두 가지 이유로 기존 졸부 코드랑 비슷하게 width 19%, width 33%로 가져갔습니다
더 좋은 방법이 있을까요? 
 1. table 사용시 rounded 적용 문제
 2. list row만 사용하는 컴포넌트 존재 

## 🔊 도움이 필요한 부분
- select component와 아래 두 아티클을 참고해서 compound component pattern을 적용해보았습니다!
 object.assign 사용하지 않는게 더 한 눈에 들어오는 것 같아서 사용하지는 않았는데, select component랑 비슷한 구현 방식을 가져가는게 통일성에 더 좋을까요??
https://fe-developers.kakaoent.com/2022/220731-composition-component/
https://im-developer.tistory.com/238

2024-02-17 08:01 UTC, seonghunYang requested changes

2024-02-17 08:01 UTC, seonghunYang commented on app/ui/view/molecule/list/list-header.tsx
> +export function ListHeader({ columns }: ListHeaderProps) {
[requset change]
- 버튼 컴포넌트에서 본 것처럼, named export를 사용하여 컴포넌트를 내보내는 것을 지향하는 이유가 있나요?
- 저는 React와 Next에서 기본적으로 생성하는 템플릿이 export default이기 때문에, 이를 표준으로 사용하는 것을 제안합니다.
- 또한, 추가적으로 컴파운드 패턴을 사용할 때는, 하위 컴포넌트에 named export를 사용하고, 컴파운드 패턴의 루트 컴포넌트에는 default export를 적용하면 컴포넌트를 분리하는 것이 더 명확해질 것이라고 생각합니다.

2024-02-17 08:06 UTC, seonghunYang commented on app/ui/view/molecule/list/list-header.tsx
> +export function ListHeader({ columns }: ListHeaderProps) {
- 추가로, default export를 사용하면 파일이 하나의 책임만을 가지도록 어느 정도 강제할 수 있어 좋다고 생각합니다.
- 만약 컴포넌트 파일에서 여러 함수나 타입 컴포넌트를 export하고 있다면, 관심사의 분리가 잘 이루어지지 않았다고 판단될 수 있습니다. 따라서 이를 방지하는 데에도 유용하다고 생각합니다.

2024-02-18 05:08 UTC, yougyung approved these changes

2024-02-18 05:08 UTC, yougyung commented on app/ui/view/molecule/list/index.tsx
> +type ListProps = {
type 및 interface 중 적용하시는 기준이 있으신가요?

2024-02-18 07:30 UTC, gahyuun commented on app/ui/view/molecule/list/index.tsx
> +type ListProps = {
interface나 type 어떤 걸 사용하던 상관이 없을 때는 통일성을 위해 팀원들과 맞춰 사용하는 편입니다
해당 코드에서는 select component와 통일성을 위해서 type을 사용했습니다!

2024-02-18 07:48 UTC, yougyung commented
> list molecule component 구현
추가,삭제 버튼이 list row에 존재할 수 있도록 수정이 필요합니다!
이 부분은 기이수 과목 삭제 기능을 구현하면서 수정 할 예정입니다

버튼 기능은 순수하게 list가 하는 역할이 아닌데, 기존 코드에서는 역할 이상을 list component가 해주고 있다고 느꼈습니다. 리스트내 버튼 기능을 추가하기 위해서 또 다른 컴포넌트를 만들어주어야하지만, list component에 button이 없는 현재 상태도 충분하다고 생각합니다.

2024-02-18 08:28 UTC, gahyuun commented
> > list molecule component 구현
> > 추가,삭제 버튼이 list row에 존재할 수 있도록 수정이 필요합니다!
> > 이 부분은 기이수 과목 삭제 기능을 구현하면서 수정 할 예정입니다
> 
> 버튼 기능은 순수하게 list가 하는 역할이 아닌데, 기존 코드에서는 역할 이상을 list component가 해주고 있다고 느꼈습니다. 리스트내 버튼 기능을 추가하기 위해서 또 다른 컴포넌트를 만들어주어야하지만, list component에 button이 없는 현재 상태도 충분하다고 생각합니다.

저는 아래와 같이 코드를 구현하려 했습니다

```
    const rowColumns = ['HEC01302', '분산프로그래밍', '3'];
    return (
      <div>
        <List>
          <List.Row columns={rowColumns} invalid={true} actionButton ={<Button></Button>} />
        </List>
      </div>
    );
    
export function ListRow({ columns, invalid = false, actionButton}: ListRowProps) {
  return (
    <div className="flex border-solid border-gray-300 border-b-[1px] items-center last:border-b-0">
      {columns.map((column, index) => (
        <div
          key={index}
          className={twMerge(
            'text-center my-4 font-medium text-lg text-[#2f2f2f]',
            columns.length === 5 ? 'w-[19%]' : 'w-[33%]',
            invalid ? 'text-red-500' : 'text-[#2f2f2f]',
          )}
        >
          {column}
        </div>
      ))}
      {actionButton}
    </div>
  );
}
```
위 방식은 button을 위한 component를 구현한 게 아니고 단지 list가 trigger 역할을 한다고 생각합니다! 
혹시 이 방식이 list component가 역할 이상을 해준다고 생각하신 게 맞을까요? 맞다면 button을 위해 list를 어떤 방식으로 수정하는 걸 선호하시는 지 좀 더 말씀해주실 수 있나요?

2024-02-18 08:29 UTC, gahyuun commented on app/ui/view/molecule/list/index.tsx
> +  };
디테일을 신경쓰지 못했네요 수정했습니다! 
https://github.com/Myongji-Graduate/myongji-graduate-next/pull/27/commits/91f3565edded5810b941dc0ec1d65157002f4f75

2024-02-18 08:37 UTC, gahyuun commented on app/ui/view/molecule/list/list-header.tsx
> +export function ListHeader({ columns }: ListHeaderProps) {
default export 로 수정했습니다
추가적으로 궁금한 게 있는데, compound pattern에 있어서 하위 컴포넌트라 하더라도 파일에서는 하나의 책임만 가지므로 default export 를 적용하는 게 더 좋지않을까요?? 
https://github.com/Myongji-Graduate/myongji-graduate-next/pull/27/commits/60b333c917dcc96f7d56cdc89bdcf221d00c2dcb

2024-02-18 13:33 UTC, seonghunYang commented
유경 씨의 의견과 비슷한데, actionbutton뿐만 아니라 ListRow 컴포넌트에 invalid 속성이 있는 것이 조금 어색하게 느껴집니다. 두 속성 모두 List와 ListRow보다는 기이수 과목 리스트를 위한 속성이라서 그런 것 같습니다. 제 생각에는 다음 두 가지 방안이 있을 것 같습니다:

1. List, ListRow 컴포넌트를 도메인 컴포넌트로 변경 - invalid, actionButton 속성은 범용적인 list 컴포넌트보다는 기이수 과목 리스트에 해당하는 내용이므로, 이를 도메인 컴포넌트로 변경
2. 컴포넌트 계층화 - List, ListRow를 재사용 및 확장 가능한 뷰 컴포넌트로 리팩토링하여 본래의 List, ListRow 기능에 집중하고, 이를 기반으로 기이수 과목 리스트 도메인 컴포넌트를 구현

세 분 모두 관련 사안에 대한 의견을 주셨으니 채팅으로 진행하는 것도 좋지만, 시간이 지체될 수 있으므로 보이스로 한 번 이야기해 보는 것은 어떨까요?

2024-02-18 13:34 UTC, seonghunYang commented on app/ui/view/molecule/list/list-header.tsx
> +export function ListHeader({ columns }: ListHeaderProps) {
저도 이와 비슷한 문제를 이전에 경험한 적이 있었던 것 같네요. 제가 사용한 select 컴포넌트처럼, index 파일에서 assign으로 묶어서 export default를 사용해 보시는 건 어떨까요?

2024-02-18 13:37 UTC, seonghunYang commented on app/ui/view/molecule/list/list-header.tsx
> +export function ListHeader({ columns }: ListHeaderProps) {
Compound 패턴에서 하위 컴포넌트에 named export를 사용하는 것을 제안하는 이유는, 독립적으로 사용되는 컴포넌트는 모두 default export를 하고, 하위 컴포넌트는 named export를 사용하게 되면, 다른 곳에서 import 할 때 이 컴포넌트가 독립된 컴포넌트인지, 아니면 하위 컴포넌트인지 명확하게 구분할 수 있기 때문입니다.

```tsx
import ListHeader from '../../..';  // 하위 컴포넌트인지 알 수 없음

import { ListHeader } from '../../'; // ListHeader는 하위 컴포넌트임을 알 수 있음
import List from '../../';   // List는 독립적인 컴포넌트임을 알 수 있음

```

이와 동일한 이유로, 독립적인 컴포넌트는 default export로 통일하면 구분이 더욱 명확해집니다. 따라서 List 컴포넌트를 export default로 변경하는 것이 좋아 보입니다!

2024-02-21 09:14 UTC, gahyuun commented
@yougyung @seonghunYang  list component 리팩토링을 해서 push 했습니다! 구현하면서 아래와 같은 점들을 느꼈습니다
- grid component 만큼 다른 컴포넌트를 추상화할 수 있을까? grid component의 역할이 컴포넌트로 분리할 정도의 역할일까?  라는 의문이 생겼습니다. 
하지만 여기서 큰 문제가 될 것 같지 않고 grid component가 주는 이점도 있을 것 같아서 구현했습니다
- render props pattern을 굳이 이용해야 하는 이유를 잘 모르겠어서 사용하지 않았습니다! children으로 사용해도 되는데 굳이 render 함수를 만들어야 하는 이유를 모르겠습니다 또한 List component에만 render props 패턴을 적용하기에 일관성이 떨어진다고 생각했습니다!

2024-02-22 04:24 UTC, seonghunYang approved these changes
- 확인했습니다. 고생하셨어요!

2024-02-22 04:27 UTC, yougyung approved these changes

2024-02-22 05:21 UTC, merged