grade upload/#9
Myongji-Graduate/myongji-graduate-next pull request #41
Opened 2024-03-03 04:27 UTC by yougyung

## **📌** 작업 내용

 

> 구현 내용 및 작업 했던 내역

- [x] file 유효성 검사 
- [x] file upload component 개발 및 스토리북 추가
- [x] file-upload page view 작업

## 🔊 특이 사항 및 전달하고 싶은 부분

- 본래 file-upload페이지에서 사용되는 button이 저희 서비스에서 사용되는 가장 큰 규격(lg)의 버튼으로 알고있습니다. 적용해보니 다소 크기가 큰 것 같아서 md사이즈로 변경했으며 lg사이즈에 대한 재조정이 필요할 것으로 예상됩니다. 괜찮으시다면 제가 lg 버튼 size에 한하여 임의로 조정한 이후 피드백을 다시 받는 방식도 좋을 것 같습니다. 

- api를 연결해서 각 상태에 따른 처리를 함께 진행하고 PR을 올리고 싶었는데, 논의 이후 진행하는 것이 좋을 것 같아서 연결부를 제외하고 올렸습니다. 

- 현재 유효성검사에 성공하지않은 경우 file-upload에서 에러를 반환하고있는데, error boundary를 사용해서 처리하고자 계획하고있습니다. 해당 부분은 error boundary의 구현이 완료되고 수정하도록 하겠습니다.

2024-03-13 05:55 UTC, seonghunYang reviewed
- 수고하셨습니다

2024-03-13 05:55 UTC, seonghunYang commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +  const { file, changeFile } = useFile();
[comment]
- 이 hook이 존재하는 이유가 input type=file은 uncontrolled 만 가능하기 때문에 맞나요?

2024-03-13 05:55 UTC, seonghunYang commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +  };
[request change]
- 클릭 이벤트가 아닌 onChange 이벤트 핸들러로 명칭을 변경해야 할 것 같습니다.

2024-03-13 05:55 UTC, seonghunYang commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +  };
[comment]
- changeFile 함수를 실행해도 input의 value 값이 변경되지 않는 것 같습니다. 이 경우, form을 통해 전송할 때 drag&drop 방식이 동작하나요?

2024-03-13 13:40 UTC, gahyuun approved these changes
고생하셨습니다!

2024-03-13 13:40 UTC, gahyuun commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +    const { files } = event.target as HTMLInputElement;
ChangeEvent<HTMLInputElement>로 작성하면 단언을 안해도 될 것 같네요!

2024-03-13 13:40 UTC, gahyuun commented on app/ui/lecture/upload-taken-lecture/upload-grade-card.tsx
폴더명은 upload-taken-lecture인데 컴포넌트명은 upload-grade-card로 되어있네요
lecture와 grade 가 혼재되어있어서 헷갈릴 수 있을 것 같네요!
성적 업로드라고 부르긴 하지만 사실 자신이 수강한 과목을 업로드 하는 거랑 마찬가지이니 grade를 taken-lecture 또는 lecture로 변경하는 건 어떨까요?

2024-03-13 14:10 UTC, yougyung commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +  };
<img width="462" alt="스크린샷 2024-03-13 오후 11 09 56" src="https://github.com/Myongji-Graduate/myongji-graduate-next/assets/75975946/bdf9c9b1-3455-4683-9201-b0713d25acc9">

`registUserGrade`에서  `formData.get('file')`을 확인했을 때, 정상적으로 동작하는 것을 확인하였습니다 :)

2024-03-14 02:14 UTC, seonghunYang commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +  const { file, changeFile } = useFile();
- React에서 input 태그 같은 것을 조작할 때, control 방식과 uncontrolled 방식이 있습니다. 제가 알기론, type=file인 경우에는 uncontrolled 컴포넌트만 가능하다고 알고 있습니다.
- 둘의 차이를 간단하게 설명하자면, control은 value를 직접 state로 관리하여 input에 넣는 방식이고, uncontrolled는 defaultValue를 지정한 후에는 기본 input처럼 동작하는 방식입니다.
- 질문한 이유는 type=file 태그는 uncontrolled 방식이지만, 파일의 유무에 따라 렌더링을 control해야 하기 때문에 이 hook을 만든 것인지 의도가 궁금해서 질문한 것입니다.
- 말씀해주신 관심사의 분리와 캡슐화에는 동의합니다.
- usePdfFile로 변경하는 것도 괜찮아 보입니다.

https://legacy.reactjs.org/docs/uncontrolled-components.html

2024-03-14 02:14 UTC, seonghunYang commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +  };
- 흠 그렇다면, 제 생각에는 input의 너비가 drag & drop이 있는 div를 모두 덮고 있어서, drag & drop 시에 onChange 이벤트가 작동하여 동작하는 것 같습니다.
- 따라서 2가지 문제가 있는 것으로 보입니다.
- 첫째, div에 onDrag와 onDragOver 이벤트가 작동하지 않는 것 같습니다. 이 이벤트 핸들러를 제거하고 테스트 해보시겠어요? 기능이 정상적으로 동작한다면, 이 이벤트 핸들러는 혼동을 방지하기 위해 제거해야 할 것 같습니다.
- 둘째, input의 className을 보면, 파일을 드래그 & 드랍하는 파란색 사각형의 X축 범위를 넘어서 파일을 드래그해도 파일이 업로드 될 것으로 예상됩니다. 이미지를 첨부하겠습니다. 해당 위치에 파일을 업로드할 때 파일이 업로드 되는지 확인해 주세요. 그리고 이것이 문제라고 생각한다면 수정이 필요할 것 같습니다.
![제목 없음](https://github.com/Myongji-Graduate/myongji-graduate-next/assets/52571252/993ea35c-e546-4f50-af15-05a98e81f42f)

2024-03-14 02:53 UTC, yougyung commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +  };
중요한 부분을 놓치고 있었네요 반영해서 수정했습니다. 감사합니다 !

2024-03-14 03:30 UTC, yougyung commented on app/ui/view/molecule/upload-pdf/upload-pdf.tsx
> +  const { file, changeFile } = useFile();
파일의 유무에 따라 렌더링을 control하려는 목적으로 `useState`를 사용한 것은 맞습니다. (제어 컴포넌트를 의도) 하지만, hook으로 분리한 목적은 앞서 말씀드린 관심사의 분리와 캡슐화 목적이 더 크게 작용했습니다.

아이러니하게도 의도는 일치했지만 Controlled Component, Uncontrolled Component의 개념적인 부분을 알고 개발에 적용했던 부분은 아니었는데 덕분에 공부해볼 수 있었습니다. 감사합니다 :)

2024-03-14 03:50 UTC, gahyuun commented on app/(sub-page)/grade-upload/page.tsx
> +import UploadGradeCard from '../../ui/lecture/upload-taken-lecture/upload-taken-lecture';
import문은 아직 upload grade card네요!

2024-03-14 03:50 UTC, gahyuun commented on app/(sub-page)/grade-upload/page.tsx
> +  );
혹시 페이지는 그대로 gradeupload로 가져가는 이유가 있을까요?!

2024-03-14 04:04 UTC, yougyung commented on app/(sub-page)/grade-upload/page.tsx
> +  );
`/taken-lecture-upload`보다 사용자에게 `/grade-upload` 가 더 직관적일 것 같다는 생각에 변경을 진행하지 않았습니다 !

2024-03-14 04:10 UTC, gahyuun commented on app/(sub-page)/grade-upload/page.tsx
> +  );
넵 알겠습니다!

2024-03-14 04:11 UTC, gahyuun approved these changes

2024-03-14 11:46 UTC, seonghunYang requested changes
- 조금 확인이 늦었네요.
- 수정 요청사항 남겨놨어요. 확인 부탁드릴게요

2024-03-14 11:46 UTC, seonghunYang commented on app/__test__/ui/view/upload-pdf.test.tsx
> +  });
[request change]

- 이 부분은 지금 확인해서 코멘트를 남깁니다.
- 테스트명만 보면 pdf가 아닌 파일이 업로드될 때 업로드가 안 되는 것처럼 보이지만, 테스트 내용을 보면 pdf 파일을 업로드했을 때를 테스트하는 것 같습니다.
- 두 가지 수정사항을 제안하고 싶습니다.
- 첫째, 테스트명을 변경해야 할 것 같습니다. 테스트명만 보아도 어떤 테스트인지 알 수 있어야 합니다. 테스트명에 대한 의견은 PR #42에 남겨두었으니 참고하시면 좋을 것 같습니다.
- 둘째, 추가 테스트가 필요해 보입니다. pdf 파일을 업로드했을 때와 pdf가 아닌 파일을 업로드했을 때를 테스트하는 것이 필요해 보입니다.
- 현재는 처리가 안 되어 있는 것 같은데, 성적표가 아닌 pdf가 업로드되었을 때 어떻게 처리되는지에 대한 테스트 코드도 나중에 추가되면 좋을 것 같네요.

2024-03-16 14:41 UTC, gahyuun approved these changes

2024-03-16 14:41 UTC, gahyuun commented on app/__test__/ui/view/upload-pdf.test.tsx
> +    expect(screen.queryByText('마우스로 드래그 하거나 아이콘을 눌러 추가해주세요.')).toBeInTheDocument();
getByText랑 queryByText 사용하는 기준을 여쭤봐도 될까요!?

2024-03-16 15:50 UTC, seonghunYang submitted a review, later dismissed
- 고생 많았어요

2024-03-17 05:28 UTC, seonghunYang reviewed
- 수고 많았어요.
- 그런데 도메인 컴포넌트인 upload-taken-lecture 컴포넌트가 아니라 뷰 컴포넌트인 upload-pdf 컴포넌트를 테스트한 이유가 있을까요?

2024-03-18 01:59 UTC, yougyung commented
> * 수고 많았어요.
> * 그런데 도메인 컴포넌트인 upload-taken-lecture 컴포넌트가 아니라 뷰 컴포넌트인 upload-pdf 컴포넌트를 테스트한 이유가 있을까요?

테스트를 진행하고자하는 case가 view component인 upload-pdf에 종속된다는 생각이 들어 해당 컴포넌트를 대상으로 테스트를 진행했습니다 :)

2024-03-18 02:06 UTC, yougyung commented on app/__test__/ui/view/upload-pdf.test.tsx
> +    expect(screen.queryByText('마우스로 드래그 하거나 아이콘을 눌러 추가해주세요.')).toBeInTheDocument();
개발과정에서 로직을 위해 메소드를 다르게 가져갔는데, 변경이 발생하면서 현재는 어떤 메소드를 사용해도 적용이 되는 상황입니다!

2024-03-18 10:00 UTC, seonghunYang commented
> > * 수고 많았어요.
> > * 그런데 도메인 컴포넌트인 upload-taken-lecture 컴포넌트가 아니라 뷰 컴포넌트인 upload-pdf 컴포넌트를 테스트한 이유가 있을까요?
> 
> 테스트를 진행하고자하는 case가 view component인 upload-pdf에 종속된다는 생각이 들어 해당 컴포넌트를 대상으로 테스트를 진행했습니다 :)

확인했어요

2024-03-18 10:00 UTC, seonghunYang approved these changes

2024-03-18 10:15 UTC, merged