Result detail/#64
Myongji-Graduate/myongji-graduate-next pull request #67
Opened 2024-04-03 09:29 UTC by yougyung

## **📌** 작업 내용

 

> 구현 내용 및 작업 했던 내역

- [x] 작업 내용

## 🤔 고민 했던 부분
- 고민했던 포인트가 없다면 **삭제**해도 됩니다.
- **어떤 고민**을 해서 **어떤 결과**가 나왔는지 작성해주세요.
- 경험 공유나 다른 팀원들의 생각을 들을 수 있을 것 같아요.

## 🔊 도움이 필요한 부분
- 도움이 필요한 부분이 없다면 **삭제** 해도 됩니다.
- **팀원들의 의견이 꼭 필요한 부분**을 작성해주세요.
- **팀원들은 놓치지 않고 꼭 이 항목을 보고 의견을 주세요.**

2024-04-04 04:25 UTC, gahyuun approved these changes
고생하셨습니다~!

2024-04-04 04:25 UTC, gahyuun commented on app/ui/result/result-category-modal/result-category-modal.tsx
같은 파일에서 개발한 이유가 있을까요!?

2024-04-04 04:25 UTC, gahyuun commented on app/ui/result/result-category-modal/result-category-modal.tsx
> +  const headerInfo = ['과목코드', '과목명', '학점'];
예전에 오빠가 남겨줬던 리뷰인데, headerInfo 변수를 함수 밖으로 빼서 리렌더링 할때마다 변수가 다시 할당되는 걸 막을 수 있을 것 같아요!

2024-04-04 04:25 UTC, gahyuun commented on app/(sub-page)/result/components/category-fullfill.tsx
> +function CategoryFullfill() {
Category를 꽉 채우다 라는 의미가 컴포넌트명을 봤을 땐 어떤 의미인지 한 번에 파악하기 좀 어렵지 않을까 싶어요!
Completed Category 같이 완료 의미를 담는 변수는 어떤가용?

2024-04-04 04:32 UTC, seonghunYang requested changes

2024-04-04 04:32 UTC, seonghunYang commented on app/ui/view/molecule/category-card/category-card.tsx
[request change]
- 컴포넌트 계층 간의 참조가 역전된 것 같습니다. 현재 view 컴포넌트가 domain 컴포넌트를 참조하고 있는데, 이는 설계상 문제를 초래할 수 있습니다.
- CategoryCard 컴포넌트와 ResultCategoryModal은 서로 결합될 필요가 없어 보입니다. useModal 때문에 결합되어 있는 것으로 보이니, useModal 설계를 변경해 이들의 결합을 분리하는 것이 필요해 보입니다.
- 또는, CategoryCard의 위치가 잘못 설정된 것 같습니다. 이 컴포넌트는 view 컴포넌트보다는 domain 컴포넌트에 더 적합해 보입니다.
- 두 가지 중 한 가지 방향으로 설계를 변경해야 할 것 같습니다. 아직 도메인 로직이 구현되지 않은 미완성 상태이라 그럴 수도 있겠다는 생각이 듭니다. 어떤 방향으로 설계를 고려하고 있는지 알려주시면 좋겠습니다.
- 만약 이해가 안 가거나 도움이 필요하시다면 언제든지 연락해 주세요.

2024-04-04 04:56 UTC, yougyung commented on app/(sub-page)/result/components/category-fullfill.tsx
> +function CategoryFullfill() {
`fullfill`의 달성하다 라는 의미로 사용했습니다. 의미적으로 통용되면 되는 부분이니 Complete단어가 더 직관적일 수 있겠네요 !

2024-04-04 05:20 UTC, yougyung commented on app/ui/result/result-category-modal/result-category-modal.tsx
우선 drawer의 사용이 추가된 만큼,` result-category-detail`로의 네이밍 변경을 진행하겠습니다.개발을 진행할때는 단순 반응형에 따른 변경이라고 생각해서 같은 파일에 위치시켰는데, container와 content로 분리하는 것도 하나의 방법이 될 수 있겠네요. 반응형을 담당하는 클라이언트 컴포넌트의 작업이 완료된 이후에 수정하는 것이 적절할 것 같은데 어떤가요?

2024-04-05 10:06 UTC, gahyuun commented on app/ui/result/result-category-modal/result-category-modal.tsx
혹시 분리를 한다면 어떤 이유에서 분리를 진행하는 건지 알 수 있을까요..!?

2024-04-05 10:07 UTC, gahyuun commented on app/ui/result/result-category-modal/result-category-modal.tsx
반응형 컴포넌트 작업 완료 후에 작업하는 게 더 좋을 것 같네요!

2024-04-09 04:34 UTC, closed without merging