Category lecture/#68
Myongji-Graduate/myongji-graduate-next pull request #76
Opened 2024-04-13 02:47 UTC by yougyung

## **📌** 작업 내용

https://github.com/Myongji-Graduate/myongji-graduate-next/assets/75975946/ca57ff10-415b-43ff-8919-436cd06073f1

> 구현 내용 및 작업 했던 내역

- [x] result category detail 기이수 미이수 toggle 구현
- [x] result category detail data fetching
- [ ] result category detail 기이수 미이수 toggle test
- [ ] view component Drawer 수정

## 🤔 고민 했던 부분
-  result page의 data fetching도 함께 진행하려했는데, data 변경이 크게 존재할 것으로 예상해 PR에 포함시키지않았습니다.
- 모바일의 경우 Drawer이 꽉차서 overflow시의 처리가 적절하게 이뤄지지 않는 다는 것을 확인했습니다. 이 부분은 다음 PR에서 수정 진행하겠습니다 !

2024-04-13 13:17 UTC, gahyuun reviewed
고생하셨습니다:)

2024-04-13 13:24 UTC, seonghunYang requested changes
- 수고하셨습니다.
- 네이밍 변경은 저도 적절하다고 생각합니다.

2024-04-13 13:24 UTC, seonghunYang commented on app/business/result/result.query.ts
> +};
[comment]
- 예외 처리나 인증 관련 로직이 아직 포함되지 않은 것 같습니다. 언제 이를 추가할 계획인지 알 수 있을까요?
- 인증은 Mock 개발 단계에서는 필요하지 않지만, 예외 처리는 Mock 개발 단계에서 동시에 개발하는 것이 좋다고 생각해서 질문 드려요.

2024-04-13 13:24 UTC, seonghunYang commented on app/ui/result/result-category/result-cagegory-detail-lecture.tsx
> +        <CompletedCategory />
[request change]
- 오늘 논의 과정에서 놓친 부분이 있었던 것 같네요.
- 논의 과정에서 제기된 주장들은 유효하나, 현재 다른 문제가 존재하는 것으로 보입니다. 하위 수준의 도메인 컴포넌트가 상위 수준의 페이지 컴포넌트를 참조하고 있어, 이는 계층의 역전으로 판단됩니다.
- 도메인 수준에서는 페이지에 대한 정보를 모르므로, 페이지 컴포넌트를 참조하는 것은 잠재적인 문제가 될 수 있습니다. 이 문제를 해결해야 할 것 같고, 지금은 두 가지 방법이 떠오릅니다.
- 첫 번째로, 이전에 언급했던 것처럼 completed-category를 뷰 컴포넌트로 리팩토링하는 것입니다. 이 방법은 계층간 역전 문제를 해결할 수 있지만, 이전에 유경이 언급했던 문제가 발생할 수 있습니다.
- 두 번째로는, completed-category를 ResultCategoryDetailLecture 컴포넌트 내의 하위 컴포넌트로 만드는 것입니다. 간단히 말해, 이 파일 내에서 하위 컴포넌트로 분리하는 것입니다. 도메인 컴포넌트로 두기에 애매하고, 뷰 컴포넌트로 두기에도 애매하다면, 이와 같이 같은 파일 내에서 분리하는 것도 하나의 해결 방안이 될 수 있습니다.
- 우선, 유경이가 생각해보고 의견을 남겨주면 좋겠습니다. 추가적인 설명이 필요하거나 도움이 필요하면 언제든지 연락주세요.

2024-04-13 13:24 UTC, seonghunYang commented on app/ui/result/result-category/result-category-detail-content.tsx
> +  info: ResultCategoryDetailInfo;
[comment]
- 외부에서 보았을 때, 인터페이스가 ResultCategoryDetailContent와 info 둘 뿐이기 때문에 info의 정확한 의미를 파악하기 어려웠습니다. 좀 더 구체적이고 의미를 명확히 표현하는 네이밍으로 개선하는 것이 어떨까요?

2024-04-15 01:54 UTC, yougyung commented on app/ui/result/result-category/result-category-detail-lecture-toggle.tsx
toggle 공통 컴포넌트로 작성하는 것을 고민하였으나, 
기이수 / 미이수 text가 포함되어져있어 공통 컴포넌트로 사용되기 어려울 것으로 예상해 따로 구현하지않았습니다!

2024-04-15 02:21 UTC, yougyung commented on app/business/result/result.query.ts
> +export const fetchResultCategoryDetailInfo = async (): Promise<ResultCategoryDetailInfo> => {
아니요. 해당 부분은 props를 통해 전달할 예정입니다. 
result page의 카테고리 작업을 진행하면서 쿼리스트링을 추가하겠습니다!

2024-04-15 04:29 UTC, yougyung commented on app/ui/result/result-category/result-category-detail-content.tsx
> +  info: ResultCategoryDetailInfo;
의미를 파악하기 어려울 수 있다고 느끼신 부분에 동의합니다. 
`info`의 type은
```ts
  totalCredit: number;
  takenCredit: number;
  detailCategory: ResultCategoryDetailLectures[];
  completed: boolean;
```
로 구성되어져 있습니다. 
포함하고 있는 정보의 성격이 각기 달라 구체화에 한계가 있다고 느낍니다. 
categoryInfo로의 변경을 고민하고 있으나, 구체성과 명확성에 대한 유의미한 변화 대해서는 의문이 듭니다. 혹시 더 좋은 네이밍 추천해주시면 반영하겠습니다!

2024-04-15 04:29 UTC, yougyung commented on app/business/result/result.query.ts
> +  haveToLectures: SearchedLectureInfo[];
1fd9319156691f99aff11bb6bb5dd2ed7cea8228

2024-04-15 09:59 UTC, yougyung commented on app/business/result/result.query.ts
> +};
예외 처리는 Mock 개발 단계에서 동시에 개발하는 것이 적절하다고 제안해주신 의견에 동의합니다! 개발 과정에서 고려하지 못했던 부분인데 예외처리 로직을 추가해서 다음 PR에 함께 올리겠습니다 :)

2024-04-15 11:39 UTC, seonghunYang commented on app/ui/result/result-category/result-category-detail-content.tsx
> +  info: ResultCategoryDetailInfo;
- 음.. 다시 보니 처음에 어색했던 이유는 'ResultCategoryDetailContent'와 'info'가 연결되지 않는다고 생각했기 때문인데, 제가 'info'라는 단어에 익숙하지 않아서 그런 것 같다는 생각이 드네요. 'data'로 치환해서 읽어보니 크게 문제가 없어 보입니다.
- 'info'나 'data'와 같은 간략한 약어(?) 임시 변수는 스타일 차이라고 생각됩니다. 따라서 수정하지 않아도 저는 괜찮아 보입니다. 좋은 의견 고맙습니다.

2024-04-15 11:42 UTC, seonghunYang commented on app/ui/result/result-category/result-cagegory-detail-lecture.tsx
> +        <CompletedCategory />
- 말씀하신 내용 잘 읽었습니다. 저도 동의하며, 말씀해주신 해결책을 적용하면 문제가 해결될 것 같습니다. 변경사항을 진행해주시면, 해당 확인 후 또 의견 남기도록 하겠습니다.

2024-04-15 13:28 UTC, gahyuun commented on app/ui/result/result-category/result-cagegory-detail-lecture.tsx
> +        <CompletedCategory />
도메인 컴포넌트가 페이지 컴포넌트를 참조하고 있으면 계층의 역전이 일어나고 잠재적인 문제가 발생한다고 하셨는데,
도메인 컴포넌트가 해당 페이지에서만 사용되고 여러 페이지에서 사용되지 못하는 문제 맞을까요??

2024-04-15 13:29 UTC, gahyuun submitted a review, later dismissed

2024-04-16 07:47 UTC, seonghunYang commented on app/ui/result/result-category/result-cagegory-detail-lecture.tsx
> +        <CompletedCategory />
제가 오늘 당직이라 짧게 남겨요! 좀 더 정확하게 말하면, 여러 페이지에서 사용이 불가능한 것이 아니라 여러 페이지에서 사용되면 안되는데 사용될 가능성이 있다는 것이 문제인 것 같습니다.

소프트웨어에서 계층을 나누는 것은 유사한 범주의 코드를 묶고, 계층 간 의존 관계를 명확하게 하여 코드를 이해하고 추적하기 쉽게 하려는 목적이 있습니다. 그런데 계층 간의 역전이 발생하면 다음과 같은 문제가 생길 수 있습니다.

- 먼저, 순환 의존성이 발생할 수 있습니다. 순환 의존성은 가장 해로운 결합 중 하나로, 각 파일이 독립적으로 보이면서도 강한 결합을 형성합니다.
- 계층 간의 경계가 모호해집니다. 각 계층은 각자의 논리를 가지고 있습니다. 계층 간 관계가 역전되면 그 논리가 흐려지고, 결국 스파게티 코드처럼 변질될 수 있습니다.

이 상황에서는 페이지 컴포넌트는 특정 페이지에만 존재하고, 도메인 컴포넌트는 페이지에 상관없이 특정 도메인 로직과 뷰 컴포넌트를 조합하여 도메인 목적을 달성한다는 논리를 가지고 있습니다. 그런데 도메인 컴포넌트가 페이지 컴포넌트를 참조하면 이 논리가 흐려집니다. 페이지 컴포넌트는 여러 페이지에서 참조될 수 있고, 반대로 도메인 컴포넌트는 특정 페이지에만 종속될 수 있습니다. 이런 상황이 지속되면 계층 간의 명확성이 점점 흐려져 결국 계층이 사라질 수 있습니다. 이 결과, 특정 코드를 개선하거나 버그를 추적할 때 어디를 봐야 할지 확실하지 않아지고, 확인해야 하는 코드도 늘어날 수 있습니다.

2024-04-16 11:25 UTC, seonghunYang approved these changes
- 확인했습니다. 수고 많으셨습니다

2024-04-17 00:47 UTC, gahyuun commented on app/ui/result/result-category/result-cagegory-detail-lecture.tsx
> +        <CompletedCategory />
이해됐습니다 감사합니다 👍

2024-04-17 00:48 UTC, gahyuun approved these changes

2024-04-17 00:57 UTC, merged